name: Deploy Frontend
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Install Dependencies
        run: npm install --prefix portfolio2

      - name: Build Frontend
        run: npm run build --prefix portfolio2
